# Generated by Django 4.1.4 on 2023-08-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0004_product_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery_images/', verbose_name='Gallery Image (860*860)')),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '05. Gallery',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='featured_image',
            field=models.ImageField(upload_to='products_images/', verbose_name='Featured Image (200*200)'),
        ),
    ]
