# Generated by Django 4.1.4 on 2023-08-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0006_blog_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=150)),
                ('title_description', models.TextField()),
                ('title_image', models.ImageField(upload_to='about_images/', verbose_name='Image (720*720)')),
                ('sub_title', models.CharField(max_length=150)),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('goal', models.TextField()),
            ],
            options={
                'verbose_name_plural': '03.About Page Content',
            },
        ),
        migrations.CreateModel(
            name='WeBelieveIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_set', models.CharField(max_length=200)),
                ('title_1', models.CharField(max_length=150)),
                ('text_1', models.TextField()),
                ('title_2', models.CharField(max_length=150)),
                ('text_2', models.TextField()),
                ('title_3', models.CharField(max_length=150)),
                ('text_3', models.TextField()),
            ],
            options={
                'verbose_name_plural': '04.We Believe In',
            },
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(upload_to='blogs_images/', verbose_name='Blog Image (600*450)'),
        ),
    ]
