# Generated by Django 4.1.4 on 2023-08-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('features', '0007_aboutpagecontent_webelievein_alter_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagecontent',
            name='fet_video',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aboutpagecontent',
            name='sub_image',
            field=models.ImageField(default='dsad', upload_to='about_images/', verbose_name='Image (500*600)'),
            preserve_default=False,
        ),
    ]
